keepEmptyPriority: false
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
lists:
  - hidden: false
    name: TODO
  - hidden: false
    name: DOING
  - hidden: false
    name: DONE
settings:
  journalType: Folder
  journalPath: notes
  taskPrefix: '#'
  maxLines: 6
  addNewCardsToTop: false
  newCardSyntax: MARKDOWN
  doneList: DONE
  cards:
    colors: []
  filteredLists: []
